fix(build): Check in dist/ folder (#11)
* ci: enhance test workflow with dist directory check

Adds a step to the GitHub Actions workflow to compare the expected and
actual `dist/` directories after the build process. If there are
uncommitted changes, an error message is displayed, and the process
exits with a failure status.

Additionally, renames the workflow to
'Pre merge' for clarity and updates job names for better
organization.

* build(vcs): Check in dist/

* build: Run `yarn all` on version bump

* test: Fix type issues in extract test

* ci(ts): add type-check step to CI workflow

Add a type-check step to the GitHub Actions workflow to ensure
TypeScript types are validated during the CI process. Update the
package.json to include a new script for type-checking and modify
the "all" script to run type-checking alongside other tasks. This
improves code quality and helps catch type-related issues early.

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -1,4 +1,4 @@
-name: 'build-test'
+name: 'Pre merge'
 on: # rebuild any PRs and main branch changes
   pull_request:
   push:
@@ -7,6 +7,7 @@ on: # rebuild any PRs and main branch changes
 
 jobs:
   build: # make sure build/ci work properly
+    name: Build
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
@@ -18,15 +19,37 @@ jobs:
         uses: borales/actions-yarn@v5
         with:
           cmd: install --immutable
-      - name: Run all
+      - name: Formatting
         uses: borales/actions-yarn@v5
         with:
-          cmd: all
+          cmd: format
+      - name: Run linting
+        uses: borales/actions-yarn@v5
+        with:
+          cmd: lint
+      - name: Check types
+        uses: borales/actions-yarn@v5
+        with:
+          cmd: type-check
+      - name: Run clear
+        uses: borales/actions-yarn@v5
+        with:
+          cmd: clear
+      - name: Run build
+        uses: borales/actions-yarn@v5
+        with:
+          cmd: build
+      - name: Compare the expected and actual dist/ directories
+        run: |
+          if [ "$(git diff --ignore-space-at-eol dist/ | wc -l)" -gt "0" ]; then
+            echo "::error::Detected uncommitted changes in dist/ after build.  See status below:"
+            git diff
+            exit 1
+          fi
+
   test: # make sure the action works on a clean machine without building
+    name: Run this action on itself
     runs-on: ubuntu-latest
-    env:
-      USERNAME:
-      SPECIAL:
     steps:
       - uses: actions/checkout@v4
       - name: Set Node.js 22.x
